B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:7g4Hy7kGDWpX6Q3QY7uTMhXJIzejwM2bWA==,iv:sfuYvnLuys8YI2YIEgCrHgHMwkZQzq2R6dgBBcUyKqc=,tag:MHVl61Pvi4RRZ2Sd9aOKdA==,type:str]
B2_APPLICATION_KEY: ENC[AES256_GCM,data:s5RQiYNQtKeiA32HiTXBgbS10/7ffm0AfArMUnrlbQ==,iv:oafEGVhZ9KazNjQ66Ty6s/CqMiINnqRBHsOfcEPe0F8=,tag:kAZ2FRab3PdVGhksVuayjA==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3Lc8iChoaX6nFefuug0DepggxoLS/g==,iv:tTe04KZhGt8C9yBqUP3g64HsIrTm7FkUCXjFFRLwF20=,tag:Qgd+EtC4o9bHIt99AhbgFQ==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QP5K5kjvC8p+WdHIFS6W0sz5qg==,iv:F5Sb64nI3uDg0W4DD5j9i+eAX0hc81la3o7dd8FLMA8=,tag:6N5BuiRYlhsQYGAknYu2tA==,type:str]
DIGITALOCEAN_TOKEN: ENC[AES256_GCM,data:DogZ83pDqMNhA+VYtmT8cCaws/ldJZeOj6neYiEGsaryrMSHnmTaJp9IHLslYvWGzAbh0NWddLBjKI7zaXEha7dGNE3xVdg=,iv:WwRZKCR7iFdlOX/v+oFQW+5V1GVXrJWYBAGMMD6paaA=,tag:hDLbBMFhtmS6psj9sUCnfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh726xrj4tzl778wajr40draeureqrly7c5m639tq5qhmr5sev9s7k5pd3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMGxFdDhLZFBjaWszZ2g0
            eUUyWXhDWEp6VndVOGptMitHaSs4VzYrYUJzCnYyT25mM1N0ZWZhWkUyRkZuMnB4
            bGlQaGJQQ3RDVzVXaG1QTTJKV3lmVWsKLS0tIGgwcmpveHBYTzdKRnNRMlpPSTJl
            Q2JvUWRaSmxPTnZBRStwUW55RlVEdlkKCoM/+yj3PuL3k1V2L8AylQb0oq3kfy3V
            fzAzQL6PfRCDG5H1kkmZZWrG3LcxPAgRFeU/RZYFAooHRkO+1F1GDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uqgz9ghdjx9df00hshmgmjddp57u83wwj0nu0vg8mvvkzwuydpsxfns33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL0RUcmFUQTh5U0hocWNq
            UWNtdFJ1RWFNMjFhTEUxbEFtRkpJN2cvamc0CktWS0VtcURYaVVIRGtDOHdnUHVi
            SDdUT1ZkVUE0TytXR3QvdENMa1FDSDgKLS0tIGhKbGp5cXFZZVFQTnFlYVZrQ2Rx
            ajg3RmRCN3NabU0wbjNoa29VQjlmZGMKHTiOeN6StdzhWjxkfxDu2KCjMQKAA3Cf
            Lue6y+UAl/EpFwiIAAaE7r/GHTIayLnkmebnepBvIAW9ZuTgwjgtIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T01:48:38Z"
    mac: ENC[AES256_GCM,data:XOMLpYqpLTC6x6fk3ZnkUyTEOAKLnPL9vT+jzfRS6Hh4r3aZfBX7jwZxiwonHSvg0bDM0ViC8lj5pmK0VHUTNSbT+IW9FzXBocQkcv7vUPLIdv20Y4cEmkAt9HPYMCgb29ZWeqyPMZaDzVf4f3RUY3GDoJekHwjqQXLTwFVrqis=,iv:88E+JFxQNREioXtddpNeZziFVG4pjOPN6NMua562WR4=,tag:VDc+7/VhGGY1tP34biK+3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
