keys:
- &pd-desk age12uqgz9ghdjx9df00hshmgmjddp57u83wwj0nu0vg8mvvkzwuydpsxfns33
- &pd-span age1qh726xrj4tzl778wajr40draeureqrly7c5m639tq5qhmr5sev9s7k5pd3
- &host-desk age1vqpwqc3kru8h24ek6kz5ekpztc7l6408xrexm4dcu6y5twrvnvasm3uxul
- &host-donix age1936use526xyscgwvvwx86xcs4z25vdlxt758rhhzmskr2dr56v9qppakat
- &host-htpc age1n5j5e9zghxg06n2cg7gw3xlx5zvjmx0nz862t4kcxfpkenj4wdzsz5yhcy
- &host-pi age17602hsan7zthm9jwgqmffs0k5cg0l5rtmu9vpuk5ww4cgu6m4grq97dmq3
- &host-span age1ad6arnnrtk3vd6663gre3qys36te8qdj0hckqkm3ujm6vaswkqnsmvt2he

creation_rules:
- path_regex: .envrc.sops.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
- path_regex: hosts/desk/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
    - *host-desk
- path_regex: hosts/donix/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
    - *host-donix
- path_regex: hosts/htpc/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
    - *host-htpc
- path_regex: hosts/pi/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
    - *host-pi
- path_regex: hosts/span/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
    - *host-span
- path_regex: routers/.*/secrets.yaml$
  key_groups:
  - age:
    - *pd-span
    - *pd-desk
