keys:
- &pd-armspan age1rwnm629kenfmccdkhjvslwtsqtwknw3rax52u7shw75dh8rt24gq7n5y4c
- &pd-desk age12uqgz9ghdjx9df00hshmgmjddp57u83wwj0nu0vg8mvvkzwuydpsxfns33
- &pd-span age1qh726xrj4tzl778wajr40draeureqrly7c5m639tq5qhmr5sev9s7k5pd3
- &pd-orb age1v30sfftltx4jz2f8zygwvtqxglm42lek98zt25m346pd2ln7affspsnv9z
- &yubiring age1yubikey1qwpnm5gflajwaptyzmhrapandm2flm2x97hlsps9lt3q48zkrnqvcx4qk4g
- &yubicab age1yubikey1q2m5hrmgxhhg6yzdz4y8sstucwlaklrmghl4nx69qrtyknunsd8m6ukcs8q
- &host-desk age1vqpwqc3kru8h24ek6kz5ekpztc7l6408xrexm4dcu6y5twrvnvasm3uxul
- &host-donix age1pc9nd0m9vygv8zsz756kj2t0z9ffwqjpg82c2r2n2p0y7aul4scqmmvhhq
- &host-htpc age1n5j5e9zghxg06n2cg7gw3xlx5zvjmx0nz862t4kcxfpkenj4wdzsz5yhcy
- &host-orb age1dzwcet7m26cnlpp4apk2fvrjkf6mj24x7uxnes5x44xaksd8g94s4yxm05
- &host-pi age17602hsan7zthm9jwgqmffs0k5cg0l5rtmu9vpuk5ww4cgu6m4grq97dmq3
- &host-span age1ad6arnnrtk3vd6663gre3qys36te8qdj0hckqkm3ujm6vaswkqnsmvt2he

creation_rules:
- path_regex: .envrc.sops.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
- path_regex: homes/pd/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *pd-orb
    - *yubiring
    - *yubicab
- path_regex: hosts/armspan/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    # - *host-armspan
- path_regex: hosts/desk/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-desk
- path_regex: hosts/donix/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-donix
- path_regex: hosts/htpc/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-htpc
- path_regex: hosts/orb/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-orb
- path_regex: hosts/pi/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-pi
- path_regex: hosts/span/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *yubiring
    - *yubicab
    - *host-span
- path_regex: routers/.*/secrets.yaml$
  key_groups:
  - age:
    - *pd-armspan
    - *pd-span
    - *pd-desk
    - *pd-orb
    - *yubiring
    - *yubicab
