;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-regexp
        backward-sexp
        coffee-dedent-line-backspace
        coffee-indent-shift-left
        coffee-newline-and-indent
        delete-horizontal-space
        delete-trailing-whitespace
        enh-ruby-electric-brace
        enh-ruby-forward-sexp
        forward-sexp
        go-mode-insert-and-indent
        indent-for-tab-command
        indent-new-comment-line
        js2r-extract-var
        kill-region
        kill-sentence
        kill-sexp
        lua-electric-match
        markdown-exdent-or-delete
        my-increment-number-at-point
        org-delete-char
        org-self-insert-command
        paredit-backslash
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-semicolon
        pd/join-next-line
        pd/open-line-before
        replace-string
        ruby-tools-interpolate
        ruby-tools-to-symbol
        set-rectangular-region-anchor
        sgml-slash
        smart-tab
        smarter-move-beginning-of-line
        tagedit-insert-equal
        tagedit-insert-lt
        tagedit-insert-quote
        transpose-words
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yank-rectangle
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        delete-window
        end-of-buffer
        ido-switch-buffer
        ielm
        js2-mode-show-node
        orgtbl-self-insert-command
        pd/back-to-indentation-or-beginning-of-line
        pd/shell-switcher-switch-or-new-buffer
        smex
        where-is
        ))
