;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-regexp
        coffee-dedent-line-backspace
        delete-horizontal-space
        forward-sexp
        indent-for-tab-command
        indent-new-comment-line
        js2r-extract-var
        kill-region
        kill-sentence
        kill-sexp
        org-delete-char
        org-self-insert-command
        paredit-backslash
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        pd/join-next-line
        set-rectangular-region-anchor
        sgml-slash
        smart-tab
        smarter-move-beginning-of-line
        tagedit-insert-equal
        tagedit-insert-lt
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer
        orgtbl-self-insert-command
        pd/back-to-indentation-or-beginning-of-line
        smex
        ))
