;; -*- mode: emacs-lisp -*-
(source gnu)
(source melpa)

(depends-on "cask")

; core
(depends-on "bind-key")
(depends-on "buffer-move")
(depends-on "company")
(depends-on "diminish")
(depends-on "easy-after-load")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "fuzzy")
(depends-on "ibuffer-vc")
(depends-on "multiple-cursors")
(depends-on "phi-search")
(depends-on "projectile")
(depends-on "quickref")
(depends-on "shell-switcher")
(depends-on "smex")
(depends-on "use-package")

; give in and use helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-bind-key")
(depends-on "helm-descbinds")
(depends-on "helm-describe-modes")
(depends-on "helm-flx")
(depends-on "helm-flycheck")
(depends-on "helm-fuzzier")
(depends-on "helm-mode-manager")
(depends-on "helm-mt")
(depends-on "helm-projectile")

; handy
(depends-on "ag")
(depends-on "ciel")
(depends-on "dash")
(depends-on "dash-at-point")
(depends-on "dired-details")
(depends-on "dired-details+")
(depends-on "linum-off")
(depends-on "package-build")
(depends-on "paradox")
(depends-on "pcmpl-git")
(depends-on "popwin")
(depends-on "s")
(depends-on "which-key")
(depends-on "wrap-region")
(depends-on "zoom-frm")

; pretty
(depends-on "molokai-theme")
(depends-on "smart-mode-line")

; misc dev
(depends-on "csv-mode")
(depends-on "csv-nav")
(depends-on "dockerfile-mode")
(depends-on "git-commit")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "git-timemachine")
(depends-on "json-mode")
(depends-on "json-snatcher")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "rainbow-mode")
(depends-on "repl-toggle")
(depends-on "yaml-mode")

; the world as lisp
(depends-on "elisp-slime-nav")
(depends-on "paredit")

; ruby et al.
(depends-on "bundler")
(depends-on "chruby")
(depends-on "company-inf-ruby")
(depends-on "enh-ruby-mode")
(depends-on "feature-mode")
(depends-on "inf-ruby")
(depends-on "rspec-mode")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-tools")
(depends-on "seeing-is-believing")
(depends-on "yard-mode")

; js
(depends-on "js2-mode")
(depends-on "web-mode")

; html-ish
(depends-on "emmet-mode")

; go
(depends-on "company-go")
(depends-on "go-direx")
(depends-on "go-eldoc")
(depends-on "go-mode")
(depends-on "go-playground")
(depends-on "gotest")

; rust
(depends-on "cargo")
(depends-on "racer")
(depends-on "rust-mode")

; cljs{0,1}
(depends-on "align-cljlet")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "cljr-helm")
(depends-on "helm-clojuredocs")

; the others
(depends-on "elixir-mode")
(depends-on "lua-mode")
(depends-on "terraform-mode")

; flycheck it all
(depends-on "flycheck")
(depends-on "flycheck-package")
(depends-on "flycheck-rust")

; dbs
(depends-on "company-edbi")
(depends-on "edbi")
(depends-on "pg")
