;; -*- mode: emacs-lisp -*-
(source gnu)
(source melpa)

(depends-on "cask")

; core
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "buffer-move")
(depends-on "diminish")
(depends-on "easy-after-load")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "find-file-in-repository")
(depends-on "flx-ido")
(depends-on "fuzzy")
(depends-on "ibuffer-vc")
(depends-on "multiple-cursors")
(depends-on "phi-search")
(depends-on "projectile")
(depends-on "quickref")
(depends-on "shell-switcher")
(depends-on "smex")

; handy
(depends-on "ag")
(depends-on "dash")
(depends-on "dash-at-point")
(depends-on "dired-details")
(depends-on "dired-details+")
(depends-on "melpa-upstream-visit")
(depends-on "package-build")
(depends-on "pcmpl-git")
(depends-on "s")
(depends-on "wrap-region")
(depends-on "zoom-frm")

; pretty
(depends-on "molokai-theme")
(depends-on "powerline")

; misc dev
(depends-on "csv-mode")
(depends-on "csv-nav")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "git-timemachine")
(depends-on "magit")
(depends-on "repl-toggle")
(depends-on "yaml-mode")

; the world as lisp
(depends-on "elisp-slime-nav")
(depends-on "paredit")

; ruby et al.
(depends-on "bundler")
(depends-on "chruby")
(depends-on "enh-ruby-mode")
(depends-on "feature-mode")
(depends-on "inf-ruby")
(depends-on "rinari")
(depends-on "rspec-mode")
(depends-on "ruby-tools")
(depends-on "pow")
(depends-on "projectile-rails")
(depends-on "yard-mode")

; elixir
(depends-on "elixir-mix")
(depends-on "elixir-mode")

; js
(depends-on "ac-js2")
(depends-on "coffee-mode")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "nodejs-repl")

; html (and things that compile to it)
(depends-on "haml-mode")
(depends-on "markdown-mode")
(depends-on "tagedit")
(depends-on "zencoding-mode")

; css (and things that compile to it)
(depends-on "less-css-mode")
(depends-on "rainbow-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
