groups:
- name: wg
  rules:
  # If handshake from donix isn't fresh, there's probably something
  # hosed with wg on pi, typically that pi doesn't have the expected
  # IPv6 GUA. which I'll figure out the root cause of some day.
  # presumably.
  - alert: StaleWireguardHandshake
    expr: time() - wireguard_latest_handshake_seconds{friendly_name="donix"} > (60*5)
    annotations:
      summary: donix wireguard connectivity down
      description: no wireguard handshake from donix in more than 5 minutes

- name: rtorrent
  rules:
  # rtorrent on nas is semiregularly pinned at 100% CPU and becomes wholly
  # unresponsive. i rarely notice until i'm trying to use it, at which point
  # i don't care to figure out the issue; i just bounce the container.
  # if the scrape is failing, it's probably because rtorrent itself is failing.
  - alert: RtorrentExporterScrapeFailing
    expr: up{job="rtorrent"} == 0
    for: 10m
    annotations:
      summary: rtorrent-exporter scrape failing
      description: no metrics from rtorrent-exporter for more than 10 minutes
