groups:
- name: wg
  rules:
  # If handshake from donix isn't fresh, there's probably something
  # hosed with wg on pi, typically that pi doesn't have the expected
  # IPv6 GUA. which I'll figure out the root cause of some day.
  # presumably.
  - alert: StaleWireguardHandshake
    expr: time() - wireguard_latest_handshake_seconds{friendly_name="donix"} > (60*5)
    annotations:
      summary: "donix wireguard connectivity down for {{ $value | humanizeDuration }}"

- name: nodes
  rules:
  - alert: SystemdUnitFailed
    expr: node_systemd_unit_state{state="failed"} == 1
    for: 5m
    annotations:
      summary: "{{ $labels.name }} failed on {{ $labels.instance }}"

- name: nas
  rules:
  - alert: NASRaidDegraded
    expr: raidStatus != 1
    annotations:
      summary: NAS RAID array degraded

  - alert: NASDiskUnhealthy
    expr: diskHealthStatus != 1
    annotations:
      summary: Unhealthy disk on NAS

  - alert: NASStorageSpaceLow
    expr: raidFreeSize{raidName!~"Storage Pool.*"} / raidTotalSize < 0.05
    annotations:
      summary: "{{ $value | humanizePercentage }} storage remaining on NAS"

- name: media
  rules:
  - alert: TorrentUncategorized
    expr: count(qbittorrent_torrent_info{category=""}) > 0
    for: 5m
    annotations:
      summary: Uncategorized torrent present
      description: on-add hook failed, presumably?
